/**
 * Estrutura de agentes IA do MD Assessoria — multi-vertical, agnóstica de setor.
 *
 * Adaptada da hierarquia do Fatto Crédito V2 (85 agentes em 9 setores) +
 * setores adicionais que devem existir num CRM-base profissional:
 * Suporte/CS dedicado, Segurança/LGPD, Jurídico/Compliance.
 *
 * REGRA AGNÓSTICA:
 *   - Os papéis/skills aqui NÃO mencionam termos específicos de vertical
 *     (cotas, ONU, fibra, etc). Cada vertical-app (Pandora, Fatto Crédito,
 *     futuros) sobrescreve o nome popular do agente em sua config própria.
 *   - As 12 categorias de KB consumidas vêm do catálogo genérico em
 *     `kb-mock.ts`.
 *
 * MODELO LLM por nível padrão:
 *   - CEO         → Opus 4.7 (raciocínio profundo)
 *   - Managers    → Sonnet 4.6 (orquestração + decisão)
 *   - Conversacionais de volume → Haiku 4.5 (volume + custo)
 *   - Analíticos / criação      → Sonnet 4.6
 *   - Determinísticos            → n8n_workflow (sem LLM)
 *
 * Hierarquia: Presidente humano → CEO IA → 11 Managers → ~85 Especialistas
 */

import type { LucideIcon } from "lucide-react";
import {
  Crown, Megaphone, Sparkles, PenTool, Palette, CalendarDays, TrendingUp,
  Mic, Mail, MessageSquare, Users as UsersIcon, Globe, Type, Eye,
  Search, Instagram, Hash, Facebook, Send, MousePointerClick,
  GitBranch, Bell, AlertCircle, Activity, Workflow, Repeat, LineChart,
  ThumbsUp, Share2, Briefcase, ListChecks, Handshake, FileText, Clock,
  Headphones, PhoneCall, Phone, BookOpen, Heart, Star,
  DollarSign, Calculator, Wallet, PieChart, TrendingDown, BarChart3, ShieldAlert,
  GraduationCap, UserPlus, UserCheck, Network, HeartHandshake, Megaphone as Bullhorn, ClipboardCheck,
  Code, Server, Database, Plug, Bug, Cog, Lock, Gauge, Telescope, FileCode,
  Microscope, Compass, Binoculars, ScrollText, AlignLeft, FlaskConical, Lightbulb, Library,
  Shield, ShieldCheck, AlertTriangle, Fingerprint,
  Scale, Gavel, FileSignature,
  Headphones as HeadphonesAudio,
} from "lucide-react";

export type AgenteNivel = "ceo" | "manager" | "especialista";
export type AgenteStatus = "ativo" | "treinando" | "pausado" | "rascunho";
export type ModeloLLM =
  | "claude-opus-4-7"
  | "claude-sonnet-4-6"
  | "claude-haiku-4-5"
  | "gemini"
  | "n8n_workflow"
  | "n8n_claude";

export type Setor =
  | "executivo"
  | "marketing"
  | "captacao"
  | "operacoes"
  | "comercial"
  | "suporte"
  | "financeiro"
  | "rh"
  | "tecnologia"
  | "pd"
  | "seguranca"
  | "juridico";

export interface Agente {
  codigo: string;
  nome: string;
  cargo: string;
  setor: Setor;
  nivel: AgenteNivel;
  modelo: ModeloLLM;
  status: AgenteStatus;
  icon: LucideIcon;
  manager?: string;
  descricao: string;
  skills: string[];
  tools: string[];
  kbCategorias: string[];
}

export const SETOR_INFO: Record<Setor, { label: string; cor: string; bg: string; icon: LucideIcon }> = {
  executivo:   { label: "Executivo",         cor: "text-amber-500",   bg: "bg-amber-500/10",   icon: Crown },
  marketing:   { label: "Marketing",         cor: "text-pink-500",    bg: "bg-pink-500/10",    icon: Megaphone },
  captacao:    { label: "Captação",          cor: "text-orange-500",  bg: "bg-orange-500/10",  icon: Search },
  operacoes:   { label: "Operações",         cor: "text-blue-500",    bg: "bg-blue-500/10",    icon: GitBranch },
  comercial:   { label: "Comercial",         cor: "text-emerald-500", bg: "bg-emerald-500/10", icon: Briefcase },
  suporte:     { label: "Suporte / CS",      cor: "text-sky-500",     bg: "bg-sky-500/10",     icon: Headphones },
  financeiro:  { label: "Financeiro / BI",   cor: "text-green-600",   bg: "bg-green-500/10",   icon: DollarSign },
  rh:          { label: "Pessoas / RH",      cor: "text-teal-500",    bg: "bg-teal-500/10",    icon: UsersIcon },
  tecnologia:  { label: "Tecnologia",        cor: "text-cyan-500",    bg: "bg-cyan-500/10",    icon: Code },
  pd:          { label: "P&D / Inovação",    cor: "text-violet-500",  bg: "bg-violet-500/10",  icon: FlaskConical },
  seguranca:   { label: "Segurança / LGPD",  cor: "text-rose-500",    bg: "bg-rose-500/10",     icon: Shield },
  juridico:    { label: "Jurídico",          cor: "text-indigo-500",  bg: "bg-indigo-500/10",  icon: Scale },
};

export const AGENTES: Agente[] = [
  // ===== CEO =====
  { codigo: "AG-CEO-01", nome: "Jarvis", cargo: "CEO IA", setor: "executivo", nivel: "ceo",
    modelo: "claude-opus-4-7", status: "ativo", icon: Crown,
    descricao: "Visão executiva. Recebe diretrizes do owner, orquestra managers, toma decisões estratégicas e reporta resultados.",
    skills: ["Jack Welch (resultados)", "Steve Jobs (visão/simplicidade)", "Ray Dalio (princípios)", "Reed Hastings (alta performance)", "Jensen Huang (urgência)"],
    tools: ["consultar_pipeline_geral", "consultar_financeiro", "consultar_kpis", "delegar_manager", "ler_relatorios"],
    kbCategorias: ["estrategia", "metricas", "negocio", "manifesto"] },

  // ===== 11 MANAGERS =====
  { codigo: "AG-MGR-01", nome: "Sofia", cargo: "CMO · Marketing", setor: "marketing", nivel: "manager",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: Megaphone, manager: "AG-CEO-01",
    descricao: "Define estratégia de marca, aprova conteúdo, coordena equipe de marketing, monitora brand equity.",
    skills: ["Seth Godin (permission marketing)", "Gary Vaynerchuk", "David Ogilvy", "Ann Handley"],
    tools: ["aprovar_calendario", "consultar_brand_card", "ler_performance_meta", "delegar_especialista"],
    kbCategorias: ["brand-card", "manifesto", "ofertas"] },
  { codigo: "AG-MGR-02", nome: "Lucas", cargo: "CGO · Growth & Captação", setor: "captacao", nivel: "manager",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: TrendingUp, manager: "AG-CEO-01",
    descricao: "Gerencia canais de aquisição, metas de CAC e volume, mix de canais pagos vs orgânicos.",
    skills: ["Sean Ellis (growth hacking)", "Brian Halligan (inbound)", "Andrew Chen (acquisition loops)", "Nir Eyal"],
    tools: ["consultar_canais", "ler_metrics_ads", "ajustar_budget", "delegar_especialista"],
    kbCategorias: ["ofertas", "metricas", "manifesto"] },
  { codigo: "AG-MGR-03", nome: "Marco", cargo: "COO · Operações", setor: "operacoes", nivel: "manager",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: GitBranch, manager: "AG-CEO-01",
    descricao: "Garante que o pipeline flui sem atrito. Monitora SLAs e supervisiona fluxo lead → venda.",
    skills: ["Eliyahu Goldratt (TOC)", "W. Edwards Deming (qualidade)", "Michael Gerber (E-Myth)"],
    tools: ["consultar_pipeline", "consultar_sla", "alertar_gargalo", "delegar_especialista"],
    kbCategorias: ["procedimentos", "metricas"] },
  { codigo: "AG-MGR-04", nome: "Rafael", cargo: "CSO · Comercial", setor: "comercial", nivel: "manager",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: Briefcase, manager: "AG-CEO-01",
    descricao: "Orquestra captação→fechamento. Aprova ofertas, monitora conversão por origem e gestor.",
    skills: ["Chet Holmes (Ultimate Sales Machine)", "David Sandler", "Grant Cardone (10x)", "Cialdini (influência)"],
    tools: ["consultar_pipeline_comercial", "aprovar_oferta", "escalar_humano", "delegar_especialista"],
    kbCategorias: ["planos", "ofertas", "objecoes"] },
  { codigo: "AG-MGR-05", nome: "Marina", cargo: "CCO · Customer Success", setor: "suporte", nivel: "manager",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: Heart, manager: "AG-CEO-01",
    descricao: "Saúde do cliente. NPS, retenção, churn precoce. Triagem por gravidade. Aprova retenção em risco.",
    skills: ["Lincoln Murphy (CS playbook)", "Nick Mehta (Customer Success)", "Patrick Bet-David"],
    tools: ["consultar_chamados", "consultar_nps", "alertar_churn", "delegar_especialista"],
    kbCategorias: ["procedimentos", "manutencao"] },
  { codigo: "AG-MGR-06", nome: "Enzo", cargo: "CTO · Tecnologia", setor: "tecnologia", nivel: "manager",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: Code, manager: "AG-CEO-01",
    descricao: "Garante uptime, performance e segurança. Avalia novas tecnologias. Reporta débito técnico.",
    skills: ["Werner Vogels (AWS)", "Martin Fowler (clean arch)", "Kelsey Hightower (DevOps)", "Troy Hunt (security)"],
    tools: ["consultar_uptime", "ler_logs", "abrir_incidente", "delegar_especialista"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-MGR-07", nome: "Valentina", cargo: "CFO · Financeiro & BI", setor: "financeiro", nivel: "manager",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: DollarSign, manager: "AG-CEO-01",
    descricao: "Monitora DRE, cashflow, comissões. Aprova despesas. Forecast mensal. Alerta CEO 7 dias antes de risco.",
    skills: ["Howard Marks (ciclos)", "Aswath Damodaran (valuation)", "Warren Buffett", "Peter Drucker"],
    tools: ["consultar_dre", "ler_cashflow", "aprovar_despesa", "gerar_forecast"],
    kbCategorias: ["cobranca", "metricas"] },
  { codigo: "AG-MGR-08", nome: "Isabela", cargo: "CHRO · Pessoas & Rede", setor: "rh", nivel: "manager",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: UsersIcon, manager: "AG-CEO-01",
    descricao: "Onboarding, treinamento, performance, retenção da equipe. Reporta saúde do time.",
    skills: ["Patty McCord (Netflix)", "Kim Scott (radical candor)", "Sheryl Sandberg", "Adam Grant"],
    tools: ["consultar_team_health", "ler_avaliacoes", "alertar_atrito", "delegar_especialista"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-MGR-09", nome: "Bernardo", cargo: "CDO · P&D & Inovação", setor: "pd", nivel: "manager",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: FlaskConical, manager: "AG-CEO-01",
    descricao: "Pesquisa mercado, monitora concorrentes, propõe inovações. Relatório semanal de tendências.",
    skills: ["Clayton Christensen (disrupção)", "Peter Thiel (de 0 a 1)", "Eric Ries (lean)", "Nassim Taleb"],
    tools: ["pesquisar_mercado", "monitorar_concorrentes", "propor_experimento"],
    kbCategorias: ["concorrentes", "estrategia"] },
  { codigo: "AG-MGR-10", nome: "Aurora", cargo: "CISO · Segurança & LGPD", setor: "seguranca", nivel: "manager",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: Shield, manager: "AG-CEO-01",
    descricao: "Proteção de dados, LGPD, auditoria de acessos, resposta a incidentes, gestão de identidade.",
    skills: ["Bruce Schneier (security)", "Yoshua Bengio (AI safety)", "ANPD (regulação BR)"],
    tools: ["auditar_acessos", "rodar_pentest", "responder_incidente", "validar_compliance_lgpd"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-MGR-11", nome: "Augusto", cargo: "CLO · Jurídico & Compliance", setor: "juridico", nivel: "manager",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: Scale, manager: "AG-CEO-01",
    descricao: "Revisa contratos, monitora compliance setorial, gere risco jurídico, valida copy regulatório.",
    skills: ["LGPD", "Marco Civil da Internet", "Direito do Consumidor"],
    tools: ["revisar_contrato", "validar_copy_regulatorio", "abrir_processo", "consultar_jurisprudencia"],
    kbCategorias: ["procedimentos"] },

  // ===== COMERCIAL (5) =====
  { codigo: "AG-COM-01", nome: "Diego", cargo: "Analista de Oportunidades (SDR)", setor: "comercial", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: ListChecks, manager: "AG-MGR-04",
    descricao: "Entrevista consultiva: objetivo, prazo, urgência, valor ideal. Define perfil e encaminha.",
    skills: ["SPIN Selling", "David Sandler (rapport)", "Chet Holmes"],
    tools: ["consultar_lead", "registrar_brief", "definir_perfil", "encaminhar_closer"],
    kbCategorias: ["planos", "objecoes"] },
  { codigo: "AG-COM-02", nome: "Fernanda", cargo: "Especialista de Catálogo", setor: "comercial", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: Search, manager: "AG-MGR-04",
    descricao: "Consulta catálogo de ofertas/planos/produtos. Filtra por critérios e gera comparativo.",
    skills: ["Análise de produto", "Pricing", "Curadoria de ofertas"],
    tools: ["consultar_catalogo", "filtrar_ofertas", "comparar_planos", "gerar_resumo"],
    kbCategorias: ["planos", "ofertas"] },
  { codigo: "AG-COM-03", nome: "Rafael C.", cargo: "Closer Conversacional", setor: "comercial", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: Handshake, manager: "AG-MGR-04",
    descricao: "Apresenta opções, responde objeções, conduz ao fechamento. Escala humano quando necessário.",
    skills: ["Cialdini (6 princípios)", "Chris Voss (mirroring/labeling)", "Jordan Belfort (rapport)", "Grant Cardone"],
    tools: ["enviar_proposta", "responder_objecao", "registrar_fechamento", "escalar_humano"],
    kbCategorias: ["objecoes", "ofertas", "concorrentes"] },
  { codigo: "AG-COM-04", nome: "Márcia", cargo: "Geração de Proposta (PDF)", setor: "comercial", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: FileText, manager: "AG-MGR-04",
    descricao: "Gera PDF de proposta personalizada. Envia por e-mail e WhatsApp.",
    skills: ["Template engine", "PDF rendering"],
    tools: ["gerar_proposta_pdf", "enviar_email", "enviar_whatsapp"],
    kbCategorias: ["planos", "ofertas"] },
  { codigo: "AG-COM-05", nome: "Paulo", cargo: "Follow-up Comercial", setor: "comercial", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: Clock, manager: "AG-MGR-04",
    descricao: "Sequência D+1, D+3, D+7, D+14. Detecta resposta e para. Escala leads quentes.",
    skills: ["Cadência outbound", "Behavioral triggers"],
    tools: ["enviar_followup", "detectar_resposta", "escalar_closer"],
    kbCategorias: ["ofertas"] },

  // ===== CAPTAÇÃO (15) =====
  { codigo: "AG-CAP-01", nome: "Bruno", cargo: "WhatsApp Conversational", setor: "captacao", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "ativo", icon: MessageSquare, manager: "AG-MGR-02",
    descricao: "Primeiro contato 24/7 via WhatsApp. Qualifica interesse, captura dados, encaminha.",
    skills: ["Conversação pt-BR", "Captura progressiva"],
    tools: ["responder_wa", "capturar_dados_lead", "encaminhar_qualifier"],
    kbCategorias: ["planos", "cobertura", "ofertas"] },
  { codigo: "AG-CAP-02", nome: "Mariana", cargo: "Instagram DM", setor: "captacao", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "ativo", icon: Instagram, manager: "AG-MGR-02",
    descricao: "Atende DMs do Instagram. Qualifica e encaminha.",
    skills: ["Tom Instagram", "Conversação informal"],
    tools: ["responder_ig_dm", "capturar_dados_lead", "encaminhar_qualifier"],
    kbCategorias: ["planos", "ofertas"] },
  { codigo: "AG-CAP-03", nome: "Pedro", cargo: "Instagram Comments", setor: "captacao", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: Hash, manager: "AG-MGR-02",
    descricao: "Monitora comentários com keywords. Move pra DM.",
    skills: ["Trigger por keyword"],
    tools: ["monitorar_comentarios_ig", "responder_publico", "convidar_dm"],
    kbCategorias: ["ofertas"] },
  { codigo: "AG-CAP-04", nome: "Jade", cargo: "TikTok Organic", setor: "captacao", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: Hash, manager: "AG-MGR-02",
    descricao: "Monitora comentários e DMs do TikTok. Move pro WhatsApp/email.",
    skills: ["Trigger por keyword"],
    tools: ["monitorar_tiktok", "responder_publico", "convidar_dm"],
    kbCategorias: ["ofertas"] },
  { codigo: "AG-CAP-05", nome: "Eduardo", cargo: "Facebook Messenger", setor: "captacao", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "ativo", icon: Facebook, manager: "AG-MGR-02",
    descricao: "Atende leads via Messenger. Qualifica e encaminha.",
    skills: ["Conversação pt-BR"],
    tools: ["responder_fb_messenger", "capturar_dados_lead"],
    kbCategorias: ["planos", "ofertas"] },
  { codigo: "AG-CAP-06", nome: "Larissa", cargo: "Facebook Comments", setor: "captacao", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: Hash, manager: "AG-MGR-02",
    descricao: "Monitora e responde comentários de anúncios. Move pra DM.",
    skills: ["Trigger por keyword"],
    tools: ["monitorar_fb_comments", "responder_publico"],
    kbCategorias: ["ofertas"] },
  { codigo: "AG-CAP-07", nome: "Gabriel", cargo: "Google Ads", setor: "captacao", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: Search, manager: "AG-MGR-02",
    descricao: "Gerencia campanhas Google Ads. Ajusta lances, palavras-chave, reporta CPC e conversões.",
    skills: ["Lance manual/automático", "Quality Score"],
    tools: ["ajustar_lances", "pausar_campanha", "ler_conversoes_ga"],
    kbCategorias: ["ofertas", "metricas"] },
  { codigo: "AG-CAP-08", nome: "Fernanda M.", cargo: "Meta Ads", setor: "captacao", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: Facebook, manager: "AG-MGR-02",
    descricao: "Facebook + Instagram pago. Otimiza criativos e públicos. Reporta CPL e CPA.",
    skills: ["Audience targeting", "Lookalike", "Creative testing"],
    tools: ["criar_campanha_meta", "ajustar_publico", "trocar_criativo", "ler_conversoes_capi"],
    kbCategorias: ["ofertas", "metricas"] },
  { codigo: "AG-CAP-09", nome: "Vitor", cargo: "TikTok Ads", setor: "captacao", nivel: "especialista",
    modelo: "n8n_workflow", status: "rascunho", icon: Hash, manager: "AG-MGR-02",
    descricao: "Campanhas pagas TikTok. Otimiza criativos verticais.",
    skills: ["Targeting TikTok", "Spark Ads"],
    tools: ["criar_campanha_tiktok", "ajustar_publico", "ler_conversoes"],
    kbCategorias: ["ofertas"] },
  { codigo: "AG-CAP-10", nome: "Amanda", cargo: "YouTube & Display", setor: "captacao", nivel: "especialista",
    modelo: "n8n_workflow", status: "rascunho", icon: Eye, manager: "AG-MGR-02",
    descricao: "Vídeo (YouTube) e display Google. Awareness + remarketing.",
    skills: ["Vídeo storytelling", "Display targeting"],
    tools: ["criar_campanha_video", "configurar_remarketing"],
    kbCategorias: ["ofertas"] },
  { codigo: "AG-CAP-11", nome: "Ricardo", cargo: "SMS Captação", setor: "captacao", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: MessageSquare, manager: "AG-MGR-02",
    descricao: "Disparo SMS pra listas segmentadas. Detecta opt-out.",
    skills: ["Compliance SMS BR", "Curtos com CTA"],
    tools: ["disparar_sms", "registrar_optout"],
    kbCategorias: ["ofertas"] },
  { codigo: "AG-CAP-12", nome: "Natália", cargo: "E-mail Captação", setor: "captacao", nivel: "especialista",
    modelo: "n8n_claude", status: "ativo", icon: Mail, manager: "AG-MGR-02",
    descricao: "Sequências cold + nurturing. Personaliza por origem e segmento.",
    skills: ["Cold email frameworks", "Subject lines"],
    tools: ["enviar_email_sequencia", "personalizar_copy", "ler_engajamento"],
    kbCategorias: ["ofertas"] },
  { codigo: "AG-CAP-13", nome: "Henrique", cargo: "CRO Analyst (LP)", setor: "captacao", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "treinando", icon: MousePointerClick, manager: "AG-MGR-02",
    descricao: "Analisa conversão da LP. Propõe e testa melhorias (A/B).",
    skills: ["CRO frameworks", "Heuristic eval", "Heatmap"],
    tools: ["ler_conversao_lp", "propor_ab_test", "registrar_winner"],
    kbCategorias: ["metricas"] },
  { codigo: "AG-CAP-14", nome: "Priscila", cargo: "Retargeting", setor: "captacao", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: Repeat, manager: "AG-MGR-02",
    descricao: "Reativa leads que visitaram mas não converteram. Sequências por canal.",
    skills: ["Funnel-based retarget", "Frequency cap"],
    tools: ["criar_audiencia_retarget", "disparar_sequencia"],
    kbCategorias: ["ofertas"] },
  { codigo: "AG-CAP-15", nome: "Arthur", cargo: "LinkedIn B2B", setor: "captacao", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "rascunho", icon: Briefcase, manager: "AG-MGR-02",
    descricao: "Prospecção B2B. Identifica decisores, abre conversa, qualifica.",
    skills: ["Sales Navigator workflow", "Cold connect"],
    tools: ["buscar_decisores", "enviar_inmail", "qualificar_b2b"],
    kbCategorias: ["ofertas"] },

  // ===== OPERAÇÕES (10) =====
  { codigo: "AG-OPS-01", nome: "Júlia", cargo: "Lead Qualifier", setor: "operacoes", nivel: "especialista",
    modelo: "n8n_claude", status: "ativo", icon: Activity, manager: "AG-MGR-03",
    descricao: "Score + temperatura + sugestão de abordagem. Roda em todo lead novo.",
    skills: ["Lead scoring", "BANT/MEDDIC"],
    tools: ["calcular_score", "definir_temperatura", "enriquecer_dados"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-OPS-02", nome: "Carlos", cargo: "Lead Distribution (Roleta)", setor: "operacoes", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: GitBranch, manager: "AG-MGR-03",
    descricao: "Roleta inteligente por carga + região + especialidade + horário.",
    skills: ["Round-robin ponderado", "Geo-proximity"],
    tools: ["consultar_disponibilidade", "atribuir_consultor", "registrar_distribuicao"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-OPS-03", nome: "Letícia", cargo: "Notificação ao Atendente", setor: "operacoes", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: Bell, manager: "AG-MGR-03",
    descricao: "Notifica consultor via WhatsApp + e-mail quando recebe um lead novo.",
    skills: ["Multi-canal notify"],
    tools: ["enviar_notificacao_wa", "enviar_email"],
    kbCategorias: [] },
  { codigo: "AG-OPS-04", nome: "André", cargo: "Alerta de Gestor", setor: "operacoes", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: AlertCircle, manager: "AG-MGR-03",
    descricao: "Alerta gestor quando consultor não responde lead em 2h.",
    skills: ["SLA enforcement"],
    tools: ["detectar_atraso", "alertar_gestor"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-OPS-05", nome: "Sabrina", cargo: "CRM Automation", setor: "operacoes", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: Workflow, manager: "AG-MGR-03",
    descricao: "Atualiza CRM a cada evento do pipeline. Mantém estado sincronizado.",
    skills: ["State machines"],
    tools: ["atualizar_crm", "mover_pipeline"],
    kbCategorias: [] },
  { codigo: "AG-OPS-06", nome: "Gustavo", cargo: "Follow-up Engine", setor: "operacoes", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: Clock, manager: "AG-MGR-03",
    descricao: "Cobra consultor após 24h sem interação. Escala se persistir.",
    skills: ["Cadence engine"],
    tools: ["detectar_inatividade", "cobrar_consultor", "escalar"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-OPS-07", nome: "Aline", cargo: "Lost Lead Recovery", setor: "operacoes", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "ativo", icon: Repeat, manager: "AG-MGR-03",
    descricao: "Recupera leads inativos com nova abordagem personalizada.",
    skills: ["Win-back campaigns", "Personalização contextual"],
    tools: ["identificar_dormentes", "gerar_copy_personalizada", "disparar_winback"],
    kbCategorias: ["ofertas"] },
  { codigo: "AG-OPS-08", nome: "Marcos", cargo: "Pipeline Monitor", setor: "operacoes", nivel: "especialista",
    modelo: "n8n_claude", status: "ativo", icon: LineChart, manager: "AG-MGR-03",
    descricao: "Monitora pipeline em tempo real. Prevê receita da semana. Alerta desvios.",
    skills: ["Time-series forecasting"],
    tools: ["consultar_pipeline_realtime", "prever_receita", "alertar_desvio"],
    kbCategorias: ["metricas"] },
  { codigo: "AG-OPS-09", nome: "Débora", cargo: "Pós-Venda / Onboarding", setor: "operacoes", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "ativo", icon: ThumbsUp, manager: "AG-MGR-03",
    descricao: "Onboarding do novo cliente. Coleta NPS. Confirma instalação/ativação.",
    skills: ["CS playbook", "NPS coleta"],
    tools: ["enviar_onboarding", "coletar_nps", "registrar_satisfacao"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-OPS-10", nome: "Leonardo", cargo: "Referral Engine", setor: "operacoes", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: Share2, manager: "AG-MGR-03",
    descricao: "Ativa indicações pra clientes NPS ≥ 8. Liga indicação ao indicador.",
    skills: ["Referral mechanics"],
    tools: ["identificar_promotores", "enviar_convite_indicacao", "registrar_indicacao"],
    kbCategorias: ["procedimentos"] },

  // ===== SUPORTE / CS (8) =====
  { codigo: "AG-SUP-01", nome: "Pan", cargo: "Suporte N1 (texto)", setor: "suporte", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "ativo", icon: Headphones, manager: "AG-MGR-05",
    descricao: "Atende top motivos por texto (WA/chat). Auto-resolve quando possível, escala N2.",
    skills: ["Triagem técnica", "Conversação empática", "Escalação"],
    tools: ["consultar_status_servico", "abrir_chamado", "gerar_2via", "transferir_humano"],
    kbCategorias: ["procedimentos", "manutencao", "cobranca"] },
  { codigo: "AG-SUP-02", nome: "Iara", cargo: "Suporte N2 (texto)", setor: "suporte", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "treinando", icon: Headphones, manager: "AG-MGR-05",
    descricao: "Casos técnicos avançados que N1 escalou. Diagnóstico + ação técnica.",
    skills: ["Diagnóstico avançado", "Análise de logs"],
    tools: ["consultar_logs_tecnicos", "propor_acao_tecnica", "abrir_os"],
    kbCategorias: ["procedimentos", "manutencao"] },
  { codigo: "AG-SUP-03", nome: "Athena", cargo: "Voice IA Inbound", setor: "suporte", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "rascunho", icon: PhoneCall, manager: "AG-MGR-05",
    descricao: "Atende ligações 24/7 via PABX. Triagem por intenção. Transfere humano quando preciso.",
    skills: ["TTS/STT pt-BR", "Triagem de voz", "Escalação rápida"],
    tools: ["transcrever_audio", "consultar_status_servico", "transferir_humano"],
    kbCategorias: ["procedimentos", "scripts-voz"] },
  { codigo: "AG-SUP-04", nome: "Apollo", cargo: "Voice IA Outbound", setor: "suporte", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "rascunho", icon: Phone, manager: "AG-MGR-05",
    descricao: "Liga ativa: cobrança preventiva, retenção, NPS pós-instalação. LGPD-compliant.",
    skills: ["Negociação por voz", "Compliance LGPD"],
    tools: ["realizar_chamada", "registrar_acordo", "registrar_nps"],
    kbCategorias: ["cobranca", "scripts-voz"] },
  { codigo: "AG-SUP-05", nome: "Brisa", cargo: "Knowledge Curator", setor: "suporte", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: BookOpen, manager: "AG-MGR-05",
    descricao: "Identifica gaps na KB a partir de tickets não resolvidos. Propõe novos artigos.",
    skills: ["Clusterização", "Gap analysis"],
    tools: ["analisar_tickets_nao_resolvidos", "propor_artigo_kb"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-SUP-06", nome: "Cíntia C.", cargo: "Retenção / Anti-Churn", setor: "suporte", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: HeartHandshake, manager: "AG-MGR-05",
    descricao: "Detecta sinal de saída (NPS baixo, atraso recorrente). Aborda com retenção.",
    skills: ["Churn prediction", "Negociação de retenção"],
    tools: ["consultar_sinais_churn", "propor_retencao", "escalar_humano"],
    kbCategorias: ["objecoes", "ofertas"] },
  { codigo: "AG-SUP-07", nome: "Olívia", cargo: "Customer Success Manager", setor: "suporte", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "rascunho", icon: Heart, manager: "AG-MGR-05",
    descricao: "Acompanha contas-chave. Health score + check-ins programados + expansão.",
    skills: ["CS playbook", "Account expansion"],
    tools: ["calcular_health_score", "agendar_checkin", "propor_upgrade"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-SUP-08", nome: "Estrela", cargo: "Analista de NPS / CSAT", setor: "suporte", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "ativo", icon: Star, manager: "AG-MGR-05",
    descricao: "Coleta, classifica e cruza NPS/CSAT por canal e atendente. Alerta quedas.",
    skills: ["Análise de sentimento", "NPS framework"],
    tools: ["coletar_nps", "classificar_feedback", "alertar_queda"],
    kbCategorias: ["metricas"] },

  // ===== MARKETING (14) =====
  { codigo: "AG-MKT-01", nome: "Breno", cargo: "Brand Strategist", setor: "marketing", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: Sparkles, manager: "AG-MGR-01",
    descricao: "Posicionamento, tom de voz, arquitetura de mensagens. Guarda do brand-card.",
    skills: ["Marty Neumeier (Brand Gap)", "Aaker (brand identity)", "Ries (positioning)"],
    tools: ["editar_brand_card", "validar_copy_tom", "propor_messaging"],
    kbCategorias: ["brand-card", "manifesto"] },
  { codigo: "AG-MKT-02", nome: "Helena", cargo: "Copywriter", setor: "marketing", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: PenTool, manager: "AG-MGR-01",
    descricao: "Anúncios, LPs, e-mails, SMS, WhatsApp, posts. A/B copy.",
    skills: ["Eugene Schwartz", "Halbert (direct)", "Joanna Wiebe"],
    tools: ["gerar_copy", "rodar_ab_copy", "validar_brand_card"],
    kbCategorias: ["brand-card", "ofertas", "objecoes"] },
  { codigo: "AG-MKT-03", nome: "Rafael M.", cargo: "Creative Director", setor: "marketing", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: Palette, manager: "AG-MGR-01",
    descricao: "Direção criativa, briefing de peças, storyboards de vídeo, mood-boards.",
    skills: ["Briefing creative", "Mood-board", "Storyboard"],
    tools: ["gerar_briefing", "gerar_storyboard", "validar_brand_card"],
    kbCategorias: ["brand-card"] },
  { codigo: "AG-MKT-04", nome: "Clara", cargo: "Content Strategist", setor: "marketing", nivel: "especialista",
    modelo: "n8n_claude", status: "ativo", icon: CalendarDays, manager: "AG-MGR-01",
    descricao: "Calendário editorial, pauta semanal, distribuição multicanal.",
    skills: ["Pillar/cluster", "Editorial cadence"],
    tools: ["gerar_calendario", "distribuir_multicanal"],
    kbCategorias: ["brand-card"] },
  { codigo: "AG-MKT-05", nome: "Mateus", cargo: "SEO Specialist", setor: "marketing", nivel: "especialista",
    modelo: "n8n_claude", status: "treinando", icon: Globe, manager: "AG-MGR-01",
    descricao: "Keywords, on-page, rankings, backlinks. SEO técnico + de conteúdo.",
    skills: ["Topic clusters", "Schema markup", "Core Web Vitals"],
    tools: ["pesquisar_keywords", "auditar_on_page", "monitorar_ranking"],
    kbCategorias: ["metricas"] },
  { codigo: "AG-MKT-06", nome: "Giulia", cargo: "Roteirista de Vídeo", setor: "marketing", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: Mic, manager: "AG-MGR-01",
    descricao: "Roteiros pra Reels, TikTok, YouTube. Hooks fortes nos primeiros 3s.",
    skills: ["Hook frameworks", "Beats narrativos curtos"],
    tools: ["gerar_roteiro_curto", "gerar_hooks"],
    kbCategorias: ["brand-card", "ofertas"] },
  { codigo: "AG-MKT-07", nome: "Felipe", cargo: "E-mail Marketing", setor: "marketing", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: Mail, manager: "AG-MGR-01",
    descricao: "Campanhas, segmentação, análise de abertura/clique.",
    skills: ["Lifecycle email", "Segmentation"],
    tools: ["disparar_campanha_email", "ler_metricas_email"],
    kbCategorias: ["ofertas"] },
  { codigo: "AG-MKT-08", nome: "Lara", cargo: "SMS Marketing", setor: "marketing", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: MessageSquare, manager: "AG-MGR-01",
    descricao: "Disparos pra base de clientes. Promoções, aniversários, datas-chave.",
    skills: ["Compliance SMS BR"],
    tools: ["disparar_sms_marketing"],
    kbCategorias: ["ofertas"] },
  { codigo: "AG-MKT-09", nome: "Thiago", cargo: "Influencer Manager", setor: "marketing", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "rascunho", icon: UsersIcon, manager: "AG-MGR-01",
    descricao: "Identifica creators alinhados, briefa, acompanha entregas e KPIs.",
    skills: ["Creator vetting", "Briefing influencer"],
    tools: ["buscar_creators", "gerar_briefing_creator", "ler_metricas_post"],
    kbCategorias: ["brand-card"] },
  { codigo: "AG-MKT-10", nome: "Camila", cargo: "Community Manager", setor: "marketing", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "rascunho", icon: HeartHandshake, manager: "AG-MGR-01",
    descricao: "Modera grupos WhatsApp/Telegram/Facebook. Engajamento + escuta.",
    skills: ["Comunidade pt-BR", "Moderação empática"],
    tools: ["responder_grupo", "moderar_conteudo", "alertar_gestor"],
    kbCategorias: ["brand-card"] },
  { codigo: "AG-MKT-11", nome: "Renato M.", cargo: "PR & Reputação", setor: "marketing", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "rascunho", icon: AlertCircle, manager: "AG-MGR-01",
    descricao: "Monitora menções, responde avaliações, pitches pra imprensa.",
    skills: ["Crisis comms", "PR pitching"],
    tools: ["monitorar_mencoes", "responder_avaliacao", "gerar_press_release"],
    kbCategorias: ["concorrentes"] },
  { codigo: "AG-MKT-12", nome: "Alice", cargo: "UX Writer", setor: "marketing", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "treinando", icon: Type, manager: "AG-MGR-01",
    descricao: "Microcopy do app/site/erp. Tooltips, mensagens de erro, onboarding.",
    skills: ["Microcopy", "Voice & Tone"],
    tools: ["gerar_microcopy", "validar_brand_card"],
    kbCategorias: ["brand-card"] },
  { codigo: "AG-MKT-13", nome: "Diego M.", cargo: "Podcast & Áudio", setor: "marketing", nivel: "especialista",
    modelo: "n8n_claude", status: "rascunho", icon: HeadphonesAudio, manager: "AG-MGR-01",
    descricao: "Transcrições, resumos, distribuição multi-plataforma.",
    skills: ["Show notes", "Audiograms"],
    tools: ["transcrever_episodio", "gerar_resumo", "publicar_plataformas"],
    kbCategorias: ["brand-card"] },
  { codigo: "AG-MKT-14", nome: "Beatriz", cargo: "Brand Intelligence", setor: "marketing", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: Eye, manager: "AG-MGR-01",
    descricao: "Monitora concorrentes, tendências, share of voice. Relatório semanal.",
    skills: ["Competitive intel", "Trend mining"],
    tools: ["monitorar_concorrentes", "ler_share_of_voice", "gerar_relatorio"],
    kbCategorias: ["concorrentes"] },

  // ===== TECNOLOGIA (10) =====
  { codigo: "AG-TEC-01", nome: "Caio", cargo: "Frontend Dev", setor: "tecnologia", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "rascunho", icon: Code, manager: "AG-MGR-06",
    descricao: "ERP/LP em Next.js + Tailwind. Acessibilidade e performance.",
    skills: ["React/Next.js", "Tailwind", "WCAG AA"],
    tools: ["abrir_pr", "gerar_componente", "rodar_testes"],
    kbCategorias: [] },
  { codigo: "AG-TEC-02", nome: "Bianca", cargo: "Backend Dev", setor: "tecnologia", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "rascunho", icon: Server, manager: "AG-MGR-06",
    descricao: "APIs, lógica de negócio, edge functions, contratos de API.",
    skills: ["Node/TS", "Supabase Edge", "API design"],
    tools: ["abrir_pr", "gerar_endpoint", "rodar_testes"],
    kbCategorias: [] },
  { codigo: "AG-TEC-03", nome: "Samuel", cargo: "DBA", setor: "tecnologia", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "rascunho", icon: Database, manager: "AG-MGR-06",
    descricao: "Postgres/Supabase. Migrations, índices, RLS, performance.",
    skills: ["PostgreSQL", "RLS", "pgvector"],
    tools: ["criar_migration", "analisar_explain", "ajustar_indices"],
    kbCategorias: [] },
  { codigo: "AG-TEC-04", nome: "Tainá", cargo: "Integration Dev", setor: "tecnologia", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "rascunho", icon: Plug, manager: "AG-MGR-06",
    descricao: "Integrações externas (Meta, IXC, ERPs, gateways). Auth, retry, observabilidade.",
    skills: ["OAuth/JWT", "Webhooks", "Rate limiting"],
    tools: ["criar_integracao", "configurar_webhook", "monitorar_latencia"],
    kbCategorias: [] },
  { codigo: "AG-TEC-05", nome: "Igor", cargo: "QA Engineer", setor: "tecnologia", nivel: "especialista",
    modelo: "n8n_claude", status: "rascunho", icon: Bug, manager: "AG-MGR-06",
    descricao: "Testes automatizados (Playwright/Vitest), regression, relatório de bugs.",
    skills: ["E2E testing", "Test pyramid"],
    tools: ["rodar_suite", "abrir_bug", "gerar_test_plan"],
    kbCategorias: [] },
  { codigo: "AG-TEC-06", nome: "Roberta", cargo: "DevOps", setor: "tecnologia", nivel: "especialista",
    modelo: "n8n_workflow", status: "rascunho", icon: Cog, manager: "AG-MGR-06",
    descricao: "Deploy, CI/CD, infraestrutura, monitoramento.",
    skills: ["GitHub Actions", "Vercel", "IaC"],
    tools: ["disparar_deploy", "monitorar_pipeline", "rollback"],
    kbCategorias: [] },
  { codigo: "AG-TEC-07", nome: "Fábio", cargo: "AppSec", setor: "tecnologia", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "rascunho", icon: Lock, manager: "AG-MGR-06",
    descricao: "OWASP, dependency scanning, code review focado em segurança.",
    skills: ["OWASP Top 10", "SAST/DAST"],
    tools: ["scan_dependencias", "code_review_security", "abrir_cve_internal"],
    kbCategorias: [] },
  { codigo: "AG-TEC-08", nome: "Vanessa", cargo: "Performance Monitor", setor: "tecnologia", nivel: "especialista",
    modelo: "n8n_workflow", status: "rascunho", icon: Gauge, manager: "AG-MGR-06",
    descricao: "Uptime, latência, Core Web Vitals. Alertas ao CTO.",
    skills: ["RUM", "Synthetic monitoring"],
    tools: ["monitorar_uptime", "monitorar_cwv", "alertar_cto"],
    kbCategorias: [] },
  { codigo: "AG-TEC-09", nome: "Rodrigo", cargo: "Tech Researcher", setor: "tecnologia", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "rascunho", icon: Telescope, manager: "AG-MGR-06",
    descricao: "Avalia novas tecnologias e LLMs. Propõe upgrades. Roadmap técnico.",
    skills: ["Tech radar", "Spike framework"],
    tools: ["pesquisar_tech", "rodar_spike", "propor_upgrade"],
    kbCategorias: ["estrategia"] },
  { codigo: "AG-TEC-10", nome: "Estela", cargo: "Documentation", setor: "tecnologia", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "rascunho", icon: FileCode, manager: "AG-MGR-06",
    descricao: "Documentação técnica do ERP, APIs e agentes. Sempre atualizada.",
    skills: ["Documentation as code", "Diátaxis"],
    tools: ["gerar_doc", "atualizar_changelog"],
    kbCategorias: [] },

  // ===== FINANCEIRO (8) =====
  { codigo: "AG-FIN-01", nome: "Adriana", cargo: "DRE Monitor", setor: "financeiro", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: PieChart, manager: "AG-MGR-07",
    descricao: "Monitora DRE em tempo real. Identifica desvios. Alerta CFO e CEO.",
    skills: ["Plano de contas 4 níveis", "Análise de variação"],
    tools: ["consultar_dre", "comparar_orcado_realizado", "alertar_desvio"],
    kbCategorias: ["metricas"] },
  { codigo: "AG-FIN-02", nome: "Murilo", cargo: "Cálculo de Comissões", setor: "financeiro", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: Calculator, manager: "AG-MGR-07",
    descricao: "Calcula e processa comissões automaticamente. Auditável e versionado.",
    skills: ["Triggers SQL", "Reconciliação"],
    tools: ["calcular_comissao", "registrar_lote_pagamento"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-FIN-03", nome: "Cristina", cargo: "Cost Monitor", setor: "financeiro", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "ativo", icon: TrendingDown, manager: "AG-MGR-07",
    descricao: "Monitora gastos por categoria. Identifica overspend e fraude potencial.",
    skills: ["Anomaly detection", "Categorização"],
    tools: ["consultar_despesas", "detectar_overspend", "alertar"],
    kbCategorias: ["metricas"] },
  { codigo: "AG-FIN-04", nome: "Danilo", cargo: "KPI Dashboard", setor: "financeiro", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: BarChart3, manager: "AG-MGR-07",
    descricao: "Atualiza KPIs em tempo real (vendas, CAC, LTV, churn).",
    skills: ["KPI engineering"],
    tools: ["atualizar_kpis", "publicar_dashboards"],
    kbCategorias: ["metricas"] },
  { codigo: "AG-FIN-05", nome: "Patrícia", cargo: "Forecast Analyst", setor: "financeiro", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "treinando", icon: LineChart, manager: "AG-MGR-07",
    descricao: "Projeção de receita 30/60/90 dias. Cenários otimista/realista/conservador.",
    skills: ["Time series", "Scenario planning"],
    tools: ["gerar_forecast", "rodar_cenarios"],
    kbCategorias: ["metricas"] },
  { codigo: "AG-FIN-06", nome: "Sérgio", cargo: "BI Insights", setor: "financeiro", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: BarChart3, manager: "AG-MGR-07",
    descricao: "Cruza vendas + leads + canais. Insights semanais com proposta de ação.",
    skills: ["Cohort analysis", "Funnel analysis"],
    tools: ["gerar_relatorio_semanal", "propor_acao"],
    kbCategorias: ["metricas"] },
  { codigo: "AG-FIN-07", nome: "Michele", cargo: "Cashflow Monitor", setor: "financeiro", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: Wallet, manager: "AG-MGR-07",
    descricao: "Entradas e saídas. Alerta risco de caixa com 7 dias de antecedência.",
    skills: ["Cashflow projection"],
    tools: ["projetar_caixa", "alertar_risco_caixa"],
    kbCategorias: ["metricas"] },
  { codigo: "AG-FIN-08", nome: "Augusto F.", cargo: "Auditoria Financeira", setor: "financeiro", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "rascunho", icon: ShieldAlert, manager: "AG-MGR-07",
    descricao: "Auditoria interna, conciliação bancária, normas setoriais (BACEN/SUSEP/Receita).",
    skills: ["Auditoria financeira", "Conciliação"],
    tools: ["conciliar_extrato", "auditar_lancamentos"],
    kbCategorias: ["procedimentos"] },

  // ===== PESSOAS / RH (7) =====
  { codigo: "AG-RH-01", nome: "Viviane", cargo: "Onboarding Specialist", setor: "rh", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "ativo", icon: UserPlus, manager: "AG-MGR-08",
    descricao: "Boas-vindas, sequência de integração, primeiro lead/tarefa, checklist de docs.",
    skills: ["Onboarding playbook", "Time-to-productivity"],
    tools: ["disparar_onboarding", "checar_docs", "agendar_treinamento"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-RH-02", nome: "Leandro", cargo: "Training Coach", setor: "rh", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: GraduationCap, manager: "AG-MGR-08",
    descricao: "Treinamento de produto, técnicas de venda, uso do ERP. Trilhas adaptativas.",
    skills: ["Bloom's taxonomy", "Spaced repetition"],
    tools: ["gerar_trilha", "avaliar_progresso", "personalizar_conteudo"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-RH-03", nome: "Mônica", cargo: "Performance Reviewer", setor: "rh", nivel: "especialista",
    modelo: "n8n_claude", status: "ativo", icon: ClipboardCheck, manager: "AG-MGR-08",
    descricao: "Avaliação mensal. Top performers + underperformers + plano de ação.",
    skills: ["OKR review", "9-box grid"],
    tools: ["gerar_review", "identificar_gap", "propor_plano_acao"],
    kbCategorias: ["metricas"] },
  { codigo: "AG-RH-04", nome: "Túlio", cargo: "Network Builder", setor: "rh", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "ativo", icon: Network, manager: "AG-MGR-08",
    descricao: "Expansão de rede (MLM/parceiros). Recrutamento por indicação. Geo + score.",
    skills: ["Geo-proximity", "Recommendation engine"],
    tools: ["sugerir_alocacao", "ativar_indicacao"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-RH-05", nome: "Cíntia R.", cargo: "Retention Specialist (interno)", setor: "rh", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "ativo", icon: HeartHandshake, manager: "AG-MGR-08",
    descricao: "Detecta sinal de saída de colaborador. Aborda com proposta de retenção.",
    skills: ["Engagement signals", "Stay interviews"],
    tools: ["identificar_risco_saida", "agendar_stay_interview"],
    kbCategorias: [] },
  { codigo: "AG-RH-06", nome: "Nelson", cargo: "Comunicação Interna", setor: "rh", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: Bullhorn, manager: "AG-MGR-08",
    descricao: "Comunicados, conquistas da semana, campanhas motivacionais nos grupos internos.",
    skills: ["Internal comms"],
    tools: ["postar_grupo", "gerar_destaques"],
    kbCategorias: [] },
  { codigo: "AG-RH-07", nome: "Soraia", cargo: "Recruiter", setor: "rh", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "rascunho", icon: UserCheck, manager: "AG-MGR-08",
    descricao: "Triagem de candidatos. Entrevista inicial. Match cultural e técnico.",
    skills: ["Behavioral interview", "Skill-match"],
    tools: ["triar_curriculos", "agendar_entrevista", "scorear_match"],
    kbCategorias: [] },

  // ===== P&D (8) =====
  { codigo: "AG-PD-01", nome: "Stella", cargo: "Market Researcher", setor: "pd", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: Microscope, manager: "AG-MGR-09",
    descricao: "TAM/SAM/SOM. Sizing de mercado. Mapeamento de segmentos.",
    skills: ["Market sizing", "Segmentation"],
    tools: ["pesquisar_mercado", "gerar_sizing"],
    kbCategorias: ["estrategia"] },
  { codigo: "AG-PD-02", nome: "Hugo", cargo: "Trend Analyst", setor: "pd", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: Compass, manager: "AG-MGR-09",
    descricao: "Tendências macro do setor + comportamento do consumidor.",
    skills: ["Trend mining", "Signal vs noise"],
    tools: ["coletar_sinais", "classificar_tendencia"],
    kbCategorias: ["estrategia"] },
  { codigo: "AG-PD-03", nome: "Carolina", cargo: "Competitor Intel", setor: "pd", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: Binoculars, manager: "AG-MGR-09",
    descricao: "Monitora concorrentes diretos e indiretos. Mapeia features, preço, copy.",
    skills: ["Competitive teardown"],
    tools: ["coletar_concorrentes", "comparar_features", "gerar_relatorio_competitive"],
    kbCategorias: ["concorrentes"] },
  { codigo: "AG-PD-04", nome: "Otávio", cargo: "Article Researcher", setor: "pd", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "ativo", icon: ScrollText, manager: "AG-MGR-09",
    descricao: "Pesquisa acadêmica e de mercado. Digest semanal pra liderança.",
    skills: ["Literature review"],
    tools: ["pesquisar_artigos", "gerar_digest"],
    kbCategorias: ["estrategia"] },
  { codigo: "AG-PD-05", nome: "Nara", cargo: "Summarizer", setor: "pd", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "ativo", icon: AlignLeft, manager: "AG-MGR-09",
    descricao: "Resume artigos, relatórios, transcrições, reuniões pra CEO e managers.",
    skills: ["Sumarização extractive+abstractive"],
    tools: ["resumir_documento", "gerar_one_pager"],
    kbCategorias: [] },
  { codigo: "AG-PD-06", nome: "Emanuel", cargo: "Technical Analyst", setor: "pd", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "rascunho", icon: FlaskConical, manager: "AG-MGR-09",
    descricao: "Laudo técnico de produtos novos, regulamentação, parecer sobre novidades.",
    skills: ["Análise técnica formal"],
    tools: ["gerar_laudo", "consultar_regulamentacao"],
    kbCategorias: ["estrategia"] },
  { codigo: "AG-PD-07", nome: "Tatiana", cargo: "Innovation Advisor", setor: "pd", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "rascunho", icon: Lightbulb, manager: "AG-MGR-09",
    descricao: "Propõe inovações, avalia viabilidade, prototipa conceitos com a equipe.",
    skills: ["Design thinking", "Lean startup"],
    tools: ["gerar_proposta_inovacao", "validar_viabilidade"],
    kbCategorias: ["estrategia"] },
  { codigo: "AG-PD-08", nome: "Davi", cargo: "Content Curator", setor: "pd", nivel: "especialista",
    modelo: "n8n_claude", status: "ativo", icon: Library, manager: "AG-MGR-09",
    descricao: "Curadoria de conteúdo (artigos, vídeos, podcasts). Calendário temático pra MKT.",
    skills: ["Editorial curation"],
    tools: ["coletar_conteudo", "ranquear_relevancia", "gerar_calendario"],
    kbCategorias: ["brand-card"] },

  // ===== SEGURANÇA / LGPD (4) =====
  { codigo: "AG-SEC-01", nome: "Orion", cargo: "Identity & Access", setor: "seguranca", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "ativo", icon: Fingerprint, manager: "AG-MGR-10",
    descricao: "Auditoria de acessos, RBAC, MFA, lifecycle de credenciais.",
    skills: ["IAM", "Zero trust"],
    tools: ["auditar_acessos", "rotacionar_credenciais", "alertar_anomalia_login"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-SEC-02", nome: "Aegis", cargo: "DPO / LGPD", setor: "seguranca", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "ativo", icon: ShieldCheck, manager: "AG-MGR-10",
    descricao: "Atende solicitações ANPD, valida finalidades, retenção de dados, DPIA.",
    skills: ["LGPD", "DPIA", "Atendimento titular"],
    tools: ["responder_titular", "validar_dpia", "gerar_relatorio_anpd"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-SEC-03", nome: "Sentinel", cargo: "SOC / Detecção", setor: "seguranca", nivel: "especialista",
    modelo: "n8n_claude", status: "rascunho", icon: AlertTriangle, manager: "AG-MGR-10",
    descricao: "Monitoramento de logs, detecção de anomalia, resposta inicial a incidentes.",
    skills: ["SIEM", "Threat intel"],
    tools: ["monitorar_logs", "detectar_anomalia", "abrir_incidente"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-SEC-04", nome: "Argo", cargo: "Audit Logger", setor: "seguranca", nivel: "especialista",
    modelo: "n8n_workflow", status: "ativo", icon: ClipboardCheck, manager: "AG-MGR-10",
    descricao: "Audit log imutável de toda escrita IA + ações de admin. Compliance + forense.",
    skills: ["Append-only logs", "Hash chains"],
    tools: ["registrar_acao", "consultar_audit_log"],
    kbCategorias: ["procedimentos"] },

  // ===== JURÍDICO (3) =====
  { codigo: "AG-JUR-01", nome: "Themis", cargo: "Contract Reviewer", setor: "juridico", nivel: "especialista",
    modelo: "claude-sonnet-4-6", status: "rascunho", icon: FileSignature, manager: "AG-MGR-11",
    descricao: "Revisa contratos com cliente/fornecedor. Sinaliza cláusulas de risco.",
    skills: ["Análise contratual", "Cláusulas abusivas"],
    tools: ["revisar_contrato", "sinalizar_risco", "sugerir_redacao"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-JUR-02", nome: "Justus", cargo: "Compliance Monitor", setor: "juridico", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "rascunho", icon: Gavel, manager: "AG-MGR-11",
    descricao: "Monitora regulação setorial (BACEN/SUSEP/ANATEL/CADE conforme vertical).",
    skills: ["Compliance setorial BR"],
    tools: ["monitorar_regulacao", "alertar_mudanca", "gerar_parecer"],
    kbCategorias: ["procedimentos"] },
  { codigo: "AG-JUR-03", nome: "Decretus", cargo: "Copy Reviewer (Regulatório)", setor: "juridico", nivel: "especialista",
    modelo: "claude-haiku-4-5", status: "rascunho", icon: ScrollText, manager: "AG-MGR-11",
    descricao: "Revisa todo copy público antes de publicar. Bloqueia claims de risco.",
    skills: ["Direito do consumidor", "Publicidade enganosa"],
    tools: ["revisar_copy_regulatorio", "bloquear_publicacao"],
    kbCategorias: ["brand-card"] },
];

export const STATUS_LABEL: Record<AgenteStatus, { label: string; cor: string; dot: string }> = {
  ativo:     { label: "Ativo",     cor: "text-emerald-600", dot: "bg-emerald-500" },
  treinando: { label: "Treinando", cor: "text-amber-600",   dot: "bg-amber-500 animate-pulse" },
  pausado:   { label: "Pausado",   cor: "text-foreground/40", dot: "bg-foreground/30" },
  rascunho:  { label: "Rascunho",  cor: "text-sky-600",     dot: "bg-sky-500" },
};

export const NIVEL_LABEL: Record<AgenteNivel, string> = {
  ceo: "CEO",
  manager: "Manager",
  especialista: "Especialista",
};

export const MODELO_LABEL: Record<ModeloLLM, string> = {
  "claude-opus-4-7": "Opus 4.7",
  "claude-sonnet-4-6": "Sonnet 4.6",
  "claude-haiku-4-5": "Haiku 4.5",
  gemini: "Gemini",
  n8n_workflow: "n8n",
  n8n_claude: "n8n + Claude",
};
